---
- name: Preflight | Validate Grafana admin password length
  ansible.builtin.assert:
    that:
      - grafana_admin_password | length >= 12
    fail_msg: "grafana_admin_password must be set and >= 12 chars."

- name: Install Grafana repo deps
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - software-properties-common
      - wget
      - gnupg
    state: present

- name: Add Grafana GPG key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana apt repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
    filename: grafana

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present
    update_cache: true

- name: Configure Grafana for subpath (/grafana/)
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: root
    mode: "0644"
  notify: restart grafana

- name: Ensure Grafana started and enabled
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: true

# - name: Inject Grafana subpath block into WordPress nginx site
#   ansible.builtin.blockinfile:
#     path: "{{ wp_nginx_site_available }}"
#     marker: "# {mark} ANSIBLE GRAFANA SUBPATH"
#     insertafter: "index index.php index.html;"
#     block: "{{ lookup('template', 'nginx_grafana_subpath.conf.j2') }}"
#   notify: reload nginx

- name: Ensure Grafana provisioning datasource dir exists
  ansible.builtin.file:
    path: /etc/grafana/provisioning/datasources
    state: directory
    owner: root
    group: grafana
    mode: "0750"

- name: Provision Prometheus datasource in Grafana
  ansible.builtin.template:
    src: datasource_prometheus.yml.j2
    dest: /etc/grafana/provisioning/datasources/prometheus.yml
    owner: root
    group: grafana
    mode: "0640"
  notify: restart grafana


- name: Include dashboard provisioning
  ansible.builtin.import_tasks: dashboards.yml
  when: monitoring_install_grafana | bool


- name: Apply restarts/reloads now
  ansible.builtin.meta: flush_handlers

- name: Validate Grafana local port is listening
  ansible.builtin.wait_for:
    host: 127.0.0.1
    port: "{{ grafana_port }}"
    timeout: 60


- name: Validate Grafana reachable via nginx subpath
  ansible.builtin.uri:
    url: "http://127.0.0.1{{ grafana_subpath }}"
    status_code: [200, 301, 302]
  register: grafana_http
  retries: 20
  delay: 3
  until: grafana_http.status in [200, 301, 302]
