---
- name: restart php-fpm
  ansible.builtin.service:
    name: php8.1-fpm
    state: restarted

- name: wordpress | validate and reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
