---
enable_monitoring: true

grafana_admin_user: admin
grafana_admin_password: ""

wp_nginx_site_available: "/etc/nginx/sites-available/wordpress"

grafana_port: 3000
grafana_subpath: "/grafana/"

# Prometheus
prometheus_config_file: "/etc/prometheus/prometheus.yml"
prometheus_port: 9090

# Exporters
install_node_exporter: true
node_exporter_port: 9100

install_mysqld_exporter: true
mysqld_exporter_port: 9104

# MySQL exporter auth (use the same root password used in mysql role)
mysql_root_password: ""

monitoring_install_prometheus: false
monitoring_install_grafana: false
monitoring_install_node_exporter: true
monitoring_install_mysqld_exporter: false   # انت مش مستخدمه
